"""
============================================================
SBA AI Studio
YouTube Metadata Generator
ML-026-004 / ML-051 (chapter wiring) / ML-058 (editable guidance)
            / ML-066 (transcript extrapolation) / ML-068 (AI
            provider wiring fix)
Version : 1.4.0
============================================================

Generates a DRAFT YouTube title, description, and tags from a
ride summary (see RideSummaryBuilder), using the app's configured
AI provider (Ollama or Groq - see ai_provider_factory.py). This is
a starting point for the channel owner to edit, not an auto-publish
pipeline - the model only knows what the ride summary tells it
(dates, duration, cameras, scene count, GPS-derived place names)
PLUS, if available, the video's own kept transcript text (see
ML-066 below) - it still can't invent specific moments, riders, or
events beyond what those sources actually say.

ML-066 (2026-07-23, per Gary's request): if a raw transcript
export AND IntelliScript's keep/cut decisions for it are both
passed to generate(), the KEPT segments (i.e. the actual final-
edit narration, in order - the same text IntelliScript's
Assembler would reassemble into a script) are extracted and fed
into the prompt as real spoken content the model can draw
specific topics, moments, comments, or phrasing from. This is
the video's own words, not invented - so the "do not invent
facts" guardrail below is extended to explicitly allow using it,
while still forbidding anything not actually said in it or given
in the ride summary/project name/notes.

If either raw_transcript_text or intelliscript_decisions is
missing (no transcript loaded yet, or IntelliScript hasn't been
generated for this project), this generator falls back to
exactly its prior behaviour - ride-summary-only, no transcript
content in the prompt at all. Re-parsing/extraction failures are
swallowed the same way chapter generation already is elsewhere -
a missing or broken transcript should degrade to the old
behaviour, never fail metadata generation outright.

MAX_TRANSCRIPT_CHARS caps how much kept-transcript text is sent
to the model, to keep the prompt (and Groq/Ollama request size)
from growing unbounded on long rides - the tail is truncated with
an explicit marker if it's cut short. Tune this constant if 12000
characters proves too small/large in practice.

ML-051/ML-052: optionally appends a chapters section to the generated
description, built from a "days"-shaped chapter list (the same shape
both ChapterGenerator and IntelliScriptChapterGenerator produce - this
generator doesn't care which one built it). This is entirely separate
from the model call: chapters are computed deterministically elsewhere,
not generated by the AI provider, and are only appended if the caller
actually has chapter data to pass in.

IMPORTANT: chapter timestamps are only as good as their source. Raw
Scene-Detection-based chapters (ChapterGenerator, ML-030) are relative
to unedited footage, not the final video - confirmed wrong for real
published videos. IntelliScriptChapterGenerator (ML-052) computes real
edited-video timestamps instead and is the preferred source; this
generator always attaches an explicit caveat regardless of source,
since it has no way to know which one produced the data it was given.

ML-058 (2026-07-23, per Gary's request): the brand-voice/style
guidance sent to the model (channel tone, title/description style, and
an instruction to naturally mention that the video was edited with SBA
AI Studio and DaVinci Resolve) is now user-editable via
app_settings.load_youtube_metadata_guidance() - the same pattern
IntelliScript's editable prompt guidance already uses. An earlier
version of this feature appended a fixed credit line deterministically
in code; Gary preferred the credit be woven naturally into the model's
own writing instead, with the ability to tune the guidance himself, so
that approach was replaced with this one.

ML-059 (2026-07-23, per Gary's SEO-expert prompt template): the
requested output is now much richer than a single title/description/
tags - 5 title options, a hook/explanation/keywords/credit/CTA/
hashtags description structure, 15 tags, a filename suggestion, a
pinned comment, and thumbnail overlay text. "title" is still returned
as a single string (the first/best pick) for backward compatibility
with existing callers; "titles" carries the full list.

ML-068 (2026-07-24, bug fix): this generator previously imported
OllamaClient directly and defaulted to a bare OllamaClient() with no
model argument whenever no client was passed in - which silently
ignored config/settings.json's "ai_provider" and "ollama_model"
settings entirely (falling back to OllamaClient's own hardcoded
"llama3.2" default no matter what Settings said). This is why
switching the Ollama model to qwen3.6 in Settings had no visible
effect for this generator specifically, while the other three
generators (which already went through get_ai_provider()) picked it
up correctly. Fixed by defaulting to get_ai_provider() instead, same
as every other AI-calling service in the app. The constructor
parameter is deliberately still named "ollama_client" (not renamed to
"ai_provider" or similar) for regression-test backward compat, same
reasoning as the other three generators.
"""

from __future__ import annotations

import json
import re

from sba_resolve.core.services.ai_provider import AIProvider
from sba_resolve.core.services.ai_provider_factory import get_ai_provider
from sba_resolve.core.services.app_settings import (
    load_youtube_metadata_guidance,
)
from sba_resolve.core.services.resolve_transcript_parser import (
    ResolveTranscriptParser,
)

# Caveat text attached to an appended chapters section. Written for
# IntelliScriptChapterGenerator's output (the only source actually
# wired in as of ML-052) - real edited-video timing, not raw footage,
# but still worth a check since it assumes the published video matches
# IntelliScript's keep/cut decisions exactly (no further manual edits
# made afterward) and topic labels are AI-generated summaries, not
# guaranteed perfect.
CHAPTERS_CAVEAT = (
    "(auto-generated from IntelliScript's edited timing - double-"
    "check against your actual published video before publishing, "
    "especially if you made further manual edits after generating "
    "IntelliScript)"
)


class YouTubeMetadataGenerator:
    """
    Generates draft YouTube title/description/tags from a ride
    summary dict (see RideSummaryBuilder.build()).
    """

    # ML-066: caps how much kept-transcript text is sent to the
    # model. Tune if this proves too small/large in practice.
    MAX_TRANSCRIPT_CHARS = 12000

    def __init__(self, ollama_client: AIProvider | None = None) -> None:
        self.ollama_client = ollama_client or get_ai_provider()

    def generate(
        self,
        ride_summary: dict,
        project_name: str,
        extra_notes: str = "",
        chapter_days: list[dict] | None = None,
        raw_transcript_text: str | None = None,
        intelliscript_decisions: dict[int, dict] | None = None,
    ) -> dict:
        """
        Returns:
            {
                "title": str | None,           # best/first title pick (backward compat)
                "titles": list[str],           # up to 5 title options
                "description": str | None,
                "tags": list[str],             # up to 15 SEO tags
                "filename_suggestion": str | None,
                "pinned_comment": str | None,
                "thumbnail_text": str | None,
                "raw_response": str,
                "parse_error": bool,
            }

        parse_error is True if the model's response couldn't be
        parsed as the requested JSON structure - raw_response is
        still returned in full so nothing is lost, the caller
        just has to read it themselves instead of getting
        structured fields.

        extra_notes: optional free text from the channel owner
        (e.g. a landmark name, an event that happened) - treated
        as trustworthy, same as the project name, NOT invented by
        the model. Pass "" if there's nothing to add.

        chapter_days: optional - the "days" list from
        ChapterGenerator.generate()'s output (i.e.
        chapter_result["days"]). If provided and non-empty, a
        chapters section is appended to the returned description,
        with an explicit raw-footage-timing caveat attached. Pass
        None (the default) to skip this entirely - e.g. when
        Planning/Scene Detection hasn't produced chapter data for
        this project yet. This append happens regardless of
        parse_error: even if the model's own response failed to
        parse, the deterministic chapter text is still useful and
        is appended after the raw response instead.

        raw_transcript_text / intelliscript_decisions (ML-066):
        both optional - if BOTH are provided, the transcript's
        KEPT segments (per intelliscript_decisions) are extracted
        and fed into the prompt as real spoken content the model
        can draw specific topics/moments/phrasing from, in
        addition to the ride summary facts. If either is missing,
        or extraction fails for any reason, this generator falls
        back to its prior ride-summary-only behaviour - this is
        never a reason to fail generation outright.
        """

        kept_transcript_text = self._extract_kept_transcript_text(
            raw_transcript_text, intelliscript_decisions
        )

        prompt = self._build_prompt(
            ride_summary, project_name, extra_notes, kept_transcript_text
        )

        raw_response = self.ollama_client.generate(prompt)

        result = self._parse_response(raw_response)

        chapters_text = self._build_chapters_section(chapter_days)

        if chapters_text:
            if result["parse_error"]:
                result["raw_response"] = (
                    f"{result['raw_response']}\n\n{chapters_text}"
                )
            else:
                existing_description = result["description"] or ""
                result["description"] = (
                    f"{existing_description}\n\n{chapters_text}"
                )

        return result

    @staticmethod
    def _build_chapters_section(chapter_days: list[dict] | None) -> str:
        """
        Builds the appended chapters text, or "" if there's
        nothing to append (no chapter data, or every day has zero
        chapters).

        For the normal case (one video = one ride day), this is
        just that single day's chapter list plus the caveat. If
        chapter_days ever contains more than one day (not expected
        in current usage - confirmed one video always covers one
        ride day - but handled defensively rather than assuming),
        each day is labeled separately; no cross-day time
        offsetting is attempted, since that would require knowing
        where one day's footage ends and the next begins in the
        FINAL video, which this generator has no way to know.
        """

        if not chapter_days:
            return ""

        day_blocks = []

        for day in chapter_days:

            if not day.get("chapters"):
                continue

            formatted = "\n".join(
                f"{chapter['time_text']} {chapter['label']}"
                for chapter in day["chapters"]
            )

            if not formatted:
                continue

            day_blocks.append(formatted)

        if not day_blocks:
            return ""

        if len(day_blocks) == 1:
            body = day_blocks[0]
        else:
            # Defensive multi-day case - not expected in current
            # usage, see docstring above.
            body = "\n\n".join(
                f"Day {day['ride_day']}:\n{block}"
                for day, block in zip(chapter_days, day_blocks)
            )

        return f"Chapters {CHAPTERS_CAVEAT}:\n{body}"

    def _extract_kept_transcript_text(
        self,
        raw_transcript_text: str | None,
        intelliscript_decisions: dict[int, dict] | None,
    ) -> str:
        """
        Returns the final-edit narration text (KEPT speech segments
        only, in index order, per intelliscript_decisions) as a
        single string, or "" if either input is missing or
        anything goes wrong while parsing/extracting.

        This mirrors what IntelliScriptAssembler would reassemble
        into a script, but simplified: just the kept words, space-
        joined, with no paragraph-break formatting - this is meant
        to be read by the model as source content, not displayed
        to a person as a script.

        Deliberately swallows all exceptions and returns "" on any
        failure (bad transcript text, mismatched decisions, etc.) -
        a broken transcript should silently fall back to the old
        ride-summary-only prompt, never break metadata generation.
        """

        if not raw_transcript_text or not intelliscript_decisions:
            return ""

        try:
            all_segments = ResolveTranscriptParser().parse(
                raw_transcript_text
            )

            kept_texts = [
                segment.text
                for segment in all_segments
                if segment.is_speech
                and intelliscript_decisions.get(segment.index, {}).get(
                    "keep"
                )
            ]

            text = " ".join(t.strip() for t in kept_texts if t.strip())

            if len(text) > self.MAX_TRANSCRIPT_CHARS:
                text = (
                    text[: self.MAX_TRANSCRIPT_CHARS].rstrip()
                    + " ...[transcript truncated]"
                )

            return text

        except Exception:
            return ""

    def _build_prompt(
        self,
        ride_summary: dict,
        project_name: str,
        extra_notes: str = "",
        kept_transcript_text: str = "",
    ) -> str:

        day_lines = []

        for day in ride_summary.get("days", []):

            parts = [f"Day {day['day']}"]

            if day.get("date"):
                parts.append(day["date"])

            parts.append(f"{day['duration_minutes']:.0f} min of footage")

            if day.get("places"):
                parts.append("places: " + ", ".join(day["places"]))
            else:
                parts.append(
                    "places: NONE IDENTIFIED - do not name a "
                    "country or region for this day (the project "
                    "name / additional notes below may still give "
                    "you a specific landmark or detail worth using)"
                )

            if day.get("cameras"):
                parts.append("cameras: " + ", ".join(day["cameras"]))

            parts.append(f"{day['scene_count']} scene(s)")

            day_lines.append(" | ".join(parts))

        days_text = "\n".join(day_lines) or "No day data available."

        total_days = ride_summary.get("total_days", 0)

        extra_notes_line = (
            f"\nAdditional notes from the channel owner (trustworthy - "
            f"use freely, but don't elaborate beyond what's written):\n"
            f"{extra_notes}\n"
            if extra_notes.strip()
            else ""
        )

        brand_voice_guidance = load_youtube_metadata_guidance()

        if kept_transcript_text:
            transcript_section = f"""
What was actually said in this video's final edit (verbatim,
real spoken narration/dialogue from the published cut - a
trustworthy primary source, same standing as the facts above):
{kept_transcript_text}
"""
            transcript_rule = (
                "\n- You MAY reference specific topics, moments, "
                "comments, jokes, or phrasing that actually appear "
                "in the \"What was actually said\" transcript above "
                "- it is real spoken content from the final video, "
                "not something to be invented. Do not reference "
                "anything beyond what it, the project name, "
                "additional notes, or day-by-day facts actually "
                "say."
            )
        else:
            transcript_section = ""
            transcript_rule = ""

        return f"""{brand_voice_guidance}

Project name: {project_name}
Total riding days: {total_days}

The project name above was written by the channel owner and may
name a real landmark, event, or place (e.g. a folder called
"12-05-2026 castle" means this ride genuinely involved a castle).
Treat specific words in the project name as a trustworthy fact you
CAN use in the title/description - do not ignore it, but also
don't invent further detail beyond what it actually says (e.g. if
it just says "castle", don't invent which castle or its history).
{extra_notes_line}
Day-by-day facts:
{days_text}
{transcript_section}
CRITICAL - do not invent facts beyond what's given above (the
project name, additional notes, day-by-day facts, and transcript
if one was provided). This is the single most important rule,
more important than the brand voice guidance above:
- For COUNTRY/REGION/CITY names: only use one if it appears in a
  day's "places" field, OR is explicitly named in the project name
  or additional notes above. Never guess one from camera brands or
  anything else.
- Do not name a specific motorcycle make or model unless one is
  given to you above.
- Do not state a distance (miles/km). Only footage DURATION in
  minutes was given to you - never convert that into a guessed
  distance or invent one separately.
- Do not name specific historical sites, landmarks, roads, or
  route names unless they appear in the places/project
  name/additional notes above.
- If you don't have a fact, write around it generically (e.g.
  "a day's ride" instead of naming a country) rather than
  inventing a specific-sounding detail.{transcript_rule}

Generate YouTube metadata for this ride video. Respond with
ONLY a JSON object, no other text, in exactly this shape:

{{
  "titles": [
    "title option 1, under 70 characters",
    "title option 2, under 70 characters",
    "title option 3, under 70 characters",
    "title option 4, under 70 characters",
    "title option 5, under 70 characters"
  ],
  "description": "a 3-5 paragraph description ending with 10-15 hashtags, per the structure above",
  "tags": ["tag1", "tag2", "... up to 15 tags total"],
  "filename_suggestion": "a short, filesystem-safe filename for the exported video, no spaces",
  "pinned_comment": "a short comment (1-3 sentences) to pin, inviting replies",
  "thumbnail_text": "3-6 words for a thumbnail overlay"
}}
"""

    @staticmethod
    def _parse_response(raw_response: str) -> dict:

        json_match = re.search(r"\{.*\}", raw_response, re.DOTALL)

        if json_match:
            try:
                data = json.loads(json_match.group(0))

                titles = data.get("titles")

                if not isinstance(titles, list):
                    titles = []

                titles = [t for t in titles if isinstance(t, str) and t.strip()]

                return {
                    "title": titles[0] if titles else None,
                    "titles": titles,
                    "description": data.get("description"),
                    "tags": data.get("tags", []),
                    "filename_suggestion": data.get("filename_suggestion"),
                    "pinned_comment": data.get("pinned_comment"),
                    "thumbnail_text": data.get("thumbnail_text"),
                    "raw_response": raw_response,
                    "parse_error": False,
                }
            except json.JSONDecodeError:
                pass

        return {
            "title": None,
            "titles": [],
            "description": None,
            "tags": [],
            "filename_suggestion": None,
            "pinned_comment": None,
            "thumbnail_text": None,
            "raw_response": raw_response,
            "parse_error": True,
        }
