"""
============================================================
SBA AI Studio
YouTube Metadata Generator
ML-026-004 / ML-051 (chapter wiring)
Version : 1.1.0 Alpha
============================================================

Generates a DRAFT YouTube title, description, and tags from a
ride summary (see RideSummaryBuilder), using a local Ollama
model. This is a starting point for the channel owner to edit,
not an auto-publish pipeline - the model only knows what the
ride summary tells it (dates, duration, cameras, scene count,
GPS-derived place names), not the actual footage content, so it
can't invent specific moments, riders, or events.

Per the project's "AI Roadmap": local AI (Ollama) by default,
cloud AI optional (not built here yet).

ML-051/ML-052: optionally appends a chapters section to the generated
description, built from a "days"-shaped chapter list (the same shape
both ChapterGenerator and IntelliScriptChapterGenerator produce - this
generator doesn't care which one built it). This is entirely separate
from the model call: chapters are computed deterministically elsewhere,
not generated by Ollama, and are only appended if the caller actually
has chapter data to pass in.

IMPORTANT: chapter timestamps are only as good as their source. Raw
Scene-Detection-based chapters (ChapterGenerator, ML-030) are relative
to unedited footage, not the final video - confirmed wrong for real
published videos. IntelliScriptChapterGenerator (ML-052) computes real
edited-video timestamps instead and is the preferred source; this
generator always attaches an explicit caveat regardless of source,
since it has no way to know which one produced the data it was given.
"""

from __future__ import annotations

import json
import re

from sba_resolve.core.services.ollama_client import OllamaClient

# Editable brand-voice guidance for the "Scottish Biker Abroad"
# channel. Tune this directly if the tone drifts - it's plain
# text, not something buried in code logic.
BRAND_VOICE_GUIDANCE = """
Channel: Scottish Biker Abroad - European motorcycle touring,
gear reviews, and ride vlogs.

Tone: irreverent British humour, self-aware about motorcycle
culture (don't take the "adventure biker" persona too
seriously), but genuinely informative for riders planning
similar trips.

Titles: SEO-focused and specific rather than vague - name the
actual place/route/landmark instead of generic phrases like
"epic ride" or "amazing day". If the ride touches WWII history
sites, castles, or other tourism crossover angles, that's worth
naming directly in the title - those searches perform well for
this channel.

Description: first 2 lines should work as a hook even if
YouTube truncates them. Include the places visited, roughly
how long/how many days, and the cameras used if that's
relevant to a gear-curious audience.
"""

# Caveat text attached to an appended chapters section. Written for
# IntelliScriptChapterGenerator's output (the only source actually
# wired in as of ML-052) - real edited-video timing, not raw footage,
# but still worth a check since it assumes the published video matches
# IntelliScript's keep/cut decisions exactly (no further manual edits
# made afterward) and topic labels are AI-generated summaries, not
# guaranteed perfect.
CHAPTERS_CAVEAT = (
    "(auto-generated from IntelliScript's edited timing - double-"
    "check against your actual published video before publishing, "
    "especially if you made further manual edits after generating "
    "IntelliScript)"
)


class YouTubeMetadataGenerator:
    """
    Generates draft YouTube title/description/tags from a ride
    summary dict (see RideSummaryBuilder.build()).
    """

    def __init__(self, ollama_client: OllamaClient | None = None) -> None:
        self.ollama_client = ollama_client or OllamaClient()

    def generate(
        self,
        ride_summary: dict,
        project_name: str,
        extra_notes: str = "",
        chapter_days: list[dict] | None = None,
    ) -> dict:
        """
        Returns:
            {
                "title": str | None,
                "description": str | None,
                "tags": list[str],
                "raw_response": str,
                "parse_error": bool,
            }

        parse_error is True if the model's response couldn't be
        parsed as the requested JSON structure - raw_response is
        still returned in full so nothing is lost, the caller
        just has to read it themselves instead of getting
        structured fields.

        extra_notes: optional free text from the channel owner
        (e.g. a landmark name, an event that happened) - treated
        as trustworthy, same as the project name, NOT invented by
        the model. Pass "" if there's nothing to add.

        chapter_days: optional - the "days" list from
        ChapterGenerator.generate()'s output (i.e.
        chapter_result["days"]). If provided and non-empty, a
        chapters section is appended to the returned description,
        with an explicit raw-footage-timing caveat attached. Pass
        None (the default) to skip this entirely - e.g. when
        Planning/Scene Detection hasn't produced chapter data for
        this project yet. This append happens regardless of
        parse_error: even if the model's own response failed to
        parse, the deterministic chapter text is still useful and
        is appended after the raw response instead.
        """

        prompt = self._build_prompt(ride_summary, project_name, extra_notes)

        raw_response = self.ollama_client.generate(prompt)

        result = self._parse_response(raw_response)

        chapters_text = self._build_chapters_section(chapter_days)

        if chapters_text:
            if result["parse_error"]:
                result["raw_response"] = (
                    f"{result['raw_response']}\n\n{chapters_text}"
                )
            else:
                existing_description = result["description"] or ""
                result["description"] = (
                    f"{existing_description}\n\n{chapters_text}"
                )

        return result

    @staticmethod
    def _build_chapters_section(chapter_days: list[dict] | None) -> str:
        """
        Builds the appended chapters text, or "" if there's
        nothing to append (no chapter data, or every day has zero
        chapters).

        For the normal case (one video = one ride day), this is
        just that single day's chapter list plus the caveat. If
        chapter_days ever contains more than one day (not expected
        in current usage - confirmed one video always covers one
        ride day - but handled defensively rather than assuming),
        each day is labeled separately; no cross-day time
        offsetting is attempted, since that would require knowing
        where one day's footage ends and the next begins in the
        FINAL video, which this generator has no way to know.
        """

        if not chapter_days:
            return ""

        day_blocks = []

        for day in chapter_days:

            if not day.get("chapters"):
                continue

            formatted = "\n".join(
                f"{chapter['time_text']} {chapter['label']}"
                for chapter in day["chapters"]
            )

            if not formatted:
                continue

            day_blocks.append(formatted)

        if not day_blocks:
            return ""

        if len(day_blocks) == 1:
            body = day_blocks[0]
        else:
            # Defensive multi-day case - not expected in current
            # usage, see docstring above.
            body = "\n\n".join(
                f"Day {day['ride_day']}:\n{block}"
                for day, block in zip(chapter_days, day_blocks)
            )

        return f"Chapters {CHAPTERS_CAVEAT}:\n{body}"

    def _build_prompt(
        self,
        ride_summary: dict,
        project_name: str,
        extra_notes: str = "",
    ) -> str:

        day_lines = []

        for day in ride_summary.get("days", []):

            parts = [f"Day {day['day']}"]

            if day.get("date"):
                parts.append(day["date"])

            parts.append(f"{day['duration_minutes']:.0f} min of footage")

            if day.get("places"):
                parts.append("places: " + ", ".join(day["places"]))
            else:
                parts.append(
                    "places: NONE IDENTIFIED - do not name a "
                    "country or region for this day (the project "
                    "name / additional notes below may still give "
                    "you a specific landmark or detail worth using)"
                )

            if day.get("cameras"):
                parts.append("cameras: " + ", ".join(day["cameras"]))

            parts.append(f"{day['scene_count']} scene(s)")

            day_lines.append(" | ".join(parts))

        days_text = "\n".join(day_lines) or "No day data available."

        total_days = ride_summary.get("total_days", 0)

        extra_notes_line = (
            f"\nAdditional notes from the channel owner (trustworthy - "
            f"use freely, but don't elaborate beyond what's written):\n"
            f"{extra_notes}\n"
            if extra_notes.strip()
            else ""
        )

        return f"""{BRAND_VOICE_GUIDANCE}

Project name: {project_name}
Total riding days: {total_days}

The project name above was written by the channel owner and may
name a real landmark, event, or place (e.g. a folder called
"12-05-2026 castle" means this ride genuinely involved a castle).
Treat specific words in the project name as a trustworthy fact you
CAN use in the title/description - do not ignore it, but also
don't invent further detail beyond what it actually says (e.g. if
it just says "castle", don't invent which castle or its history).
{extra_notes_line}
Day-by-day facts:
{days_text}

CRITICAL - do not invent facts beyond what's given above (the
project name, additional notes, and day-by-day facts). This is
the single most important rule, more important than the brand
voice guidance above:
- For COUNTRY/REGION/CITY names: only use one if it appears in a
  day's "places" field, OR is explicitly named in the project name
  or additional notes above. Never guess one from camera brands or
  anything else.
- Do not name a specific motorcycle make or model unless one is
  given to you above.
- Do not state a distance (miles/km). Only footage DURATION in
  minutes was given to you - never convert that into a guessed
  distance or invent one separately.
- Do not name specific historical sites, landmarks, roads, or
  route names unless they appear in the places/project
  name/additional notes above.
- If you don't have a fact, write around it generically (e.g.
  "a day's ride" instead of naming a country) rather than
  inventing a specific-sounding detail.

Generate YouTube metadata for this ride video. Respond with
ONLY a JSON object, no other text, in exactly this shape:

{{
  "title": "a single SEO-focused title, under 100 characters",
  "description": "a 3-5 paragraph description",
  "tags": ["tag1", "tag2", "..."]
}}
"""

    @staticmethod
    def _parse_response(raw_response: str) -> dict:

        json_match = re.search(r"\{.*\}", raw_response, re.DOTALL)

        if json_match:
            try:
                data = json.loads(json_match.group(0))

                return {
                    "title": data.get("title"),
                    "description": data.get("description"),
                    "tags": data.get("tags", []),
                    "raw_response": raw_response,
                    "parse_error": False,
                }
            except json.JSONDecodeError:
                pass

        return {
            "title": None,
            "description": None,
            "tags": [],
            "raw_response": raw_response,
            "parse_error": True,
        }
